# UBCUAS Gitlab-CI configuration

image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache bash make

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

Build Docker Multiarch:
  stage: build
  tags:
    - docker
  script:
    - make docker-multiarch

UnitTest Docker x64:
  stage: test
  tags:
    - docker
  script:
    - make ci-test

Publish Docker Multiarch:
  stage: deploy
  tags:
    - docker
  script:
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
    - make docker-multiarch-publish
  when: on_success
  only:
    - master

