[package]
name = "smurfette"
version = "0.1.0"
authors = ["Eric Mikulin"]
edition = "2018"

[dependencies]
clap = { version = "2.33.1", features = ["yaml"] }
crossbeam = "0.7.3"
reqwest = { version = "0.10.6", features = ["blocking"] }
ruuas = { path = "/opt/ruuas/" }
